baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
publishDir = "./public"

title = "Gorgonia"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "toml"
pygmentsCodeFences = true

[params]
  editURL = "https://github.com/gorgonia/gorgonia.github.io/edit/develop/content/"
  description = "Documentation for Gorgonia"
  author = "The Gorgonia Authors"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "gorgonia"

# vanity imports for Go,
# see https://npf.io/2016/10/vanity-imports-with-hugo/
[Permalinks]
  vanity-import-paths = "/:filename/"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Gorgonia"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/gorgonia/gorgonia"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Godoc"
identifier = "godoc"
url = "https://godoc.org/gorgonia.org/gorgonia"
weight = 11

[Languages.fr]
title = "Gorgonia"
weight = 2
languageName = "Fran√ßais"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/gorgonia.org/gorgonia"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Godoc"
identifier = "godoc"
url = "https://godoc.org/gorgonia.org/gorgonia"
weight = 11

