baseURL = "https://gorgonia.org/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Gorgonia - Deep Learning Library for Go"
theme = "docdock"
publishdir = "../"

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses =true
pygmentsCodeFences=true

[params]
        editURL = "https://github.com/gorgonia/gorgonia.github.io/src/content/"
        themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
        themeStyle = "flex" # "original" or "flex" # default "flex"
	author = "Gorgonia Authors"
        name = "Gorgonia"
	description = "Gorgonia is a suite of libraries for creating performant deep learning and machine learning applications in Go"
	copyright = "Released under the MIT license"

        enableGitInfo = true
        ordersectionsby = "weight" # ordersectionsby = "title"


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/gorgonia/gorgonia"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>GoDoc</label>"
identifier = "godoc"
url = "https://godoc.org/gorgonia.org/gorgonia"
weight = 20

